epochs: 100
grad_clip: -1
log_frequency: 25

criterion:
  name: CrossEntropyLoss

model:
  name: resnet18_200
  num_classes: 200

optimizer:
  name: SGD
  lr: 0.1
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: MultiStepLR
  milestones: [60, 80]
  gamma: 0.1

dataset:
  name: DatasetGenerator
  train_bs: 128
  eval_bs: 128
  n_workers: 4
  train_d_type: 'ISBBAImageNet'
  test_d_type: 'ISBBAImageNetClean'
  poison_test_d_type: 'ISBBAImageNet'
  train_tf_op: 'NoAug'
  test_tf_op: 'ISBBAImageNet'
  target_label: 0
  bd_ratio: 0.1
  train_path: '/data/gpfs/projects/punim0784/datasets/sub-imagenet-200'
  test_path: '/data/gpfs/projects/punim0784/datasets/sub-imagenet-200'
  backdoor_path: '/data/gpfs/projects/punim0784/datasets/sub-imagenet-200-bd/inject_a'
